In [1]:
import numpy as np
import sys
# from os import system
# import time

def parsemap(filename: str):
    """Obtiene un np.ndarray para representar el mapa de energías desde el
    archivo filename"""
    with open(filename) as f:
        input = f.readlines()
    energymap = []
    for s in input: 
        row = []
        for c in s: 
            if c != "\n": row.append(int(c))
        energymap.append(row)
    return np.array(energymap)

In [48]:
board = parsemap("game-life.txt")
board

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [36]:
board.shape

(10, 10)

In [40]:
count_around(board, 1, 2)

3

In [38]:
# Devuelve la cantidad de células vivas alrededor de la posición i,j
def count_around(input_board, i, j):
    m, n = board.shape
    count = 0
    for x in range(i-1,i+2):
        for y in range(j-1, j+2):
            if x == i and y == j: continue
            if x < 0 or x > (m-1) or y < 0 or y > (n-1): continue 
            # Acumular los 1s y 0s del tablero
            # print(input_board[x,y])
            count += input_board[x,y]

    return count

In [51]:
# Devuelve 1 o 0 si la celda en la posición i,j del mapa debe seguir viva o muerta
def update_alive(input_board, i, j):
    count_at_ij = count_around(input_board, i, j)
    if count_at_ij == 2 or count_at_ij == 3: 
        return 1
    return 0

# Devuelve 1 si hay 3 celulas vivas alrededor, y 0 (muere) en caso contrario
def update_death(input_board, i, j): 
    count_at_ij = count_around(input_board, i, j)
    if count_at_ij == 3: return 1
    return 0

In [53]:
def step(input_board):
    # Crear una copia del tablero
    board = input_board.copy()
    m, n = board.shape

    for i in range(m): 
        for j in range(n):
            cell = input_board[i,j]
            # print(cell)
            # Si la célula está viva: actualizarla según sus reglas
            if cell == 1: 
                board[i, j] = update_alive(input_board, i, j)
            # Si no, (está muerta) actualizarla según las reglas
            else: 
                board[i, j] = update_death(input_board, i, j)

    return board

In [54]:
board

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [55]:
step(board)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [65]:
# Actualiza el tablero después de steps pasos
def update_board(input_board, steps): 
    board = input_board.copy()
    # Iterar el tablero steps pasos
    for i in range(steps):
        board = step(board)
    
    return board

In [57]:
update_board(board, 10)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 1, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
def board_representation(input_board): 
    # 
    pass

In [62]:
# Cuente la población en steps pasos
def population_board(input_board, steps): 
    board = input_board.copy()
    population = input_board.sum()
    # Iterar el tablero steps pasos
    for i in range(steps):
        board = step(board)
        population += board.sum()
    
    return population

In [64]:
population_board(board, 100)

1543

In [66]:
update_board(board, 100)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 1, 0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])